name: Deploy Laravel to Hpanel

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Hpanel

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/u982131153/domains/artiknesia.com/
            git clone https://github.com/ahmakbardev/seniman_ARTIKNESIA.git
            cd /home/u982131153/domains/artiknesia.com/seniman_ARTIKNESIA
            chmod +x ~/bin/composer
            echo "export PATH=$HOME/bin:$PATH" >> ~/.bash_profile
            source ~/.bash_profile
            which composer
            composer --version
            composer install
            composer update
            php artisan key:generate
            php artisan route:clear
            php artisan config:cache
            php artisan optimize
            ln -s /home/u982131153/domains/artiknesia.com/seniman_ARTIKNESIA/public /home/u982131153/domains/artiknesia.com/public_html/seniman
